alter table TMBKT_TRAWL_APPLICATION add constraint FK_TMBKT_TRAWL_APPLICATION_EQUIPMENT_NAME_ID foreign key (EQUIPMENT_NAME_ID) references TMBKT_TECHNICS(ID);
alter table TMBKT_TRAWL_APPLICATION add constraint FK_TMBKT_TRAWL_APPLICATION_CARD_ID foreign key (CARD_ID) references DF_DOC(CARD_ID);
