alter table TMBKT_TRAWL_APPLICATION add constraint FK_TMBKT_TRAWL_APPLICATION_CTA_STATE foreign key (CTA_STATE) references TMBKT_TRAWL_APPLICATION(CARD_ID);
create index IDX_TMBKT_TRAWL_APPLICATION_CTA_STATE on TMBKT_TRAWL_APPLICATION (CTA_STATE);
